/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ManageNotification': EventHandler<{ name: string; email: string }, never>
    'ProcessRegisteredUser': EventHandler<{ id: number; name: string; email: string; password: string }, { topic: 'notification'; data: { name: string; email: string } }>
    'ApiTrigger': ApiRouteHandler<{ name: string; email: string; password: string }, ApiResponse<200, { id: number; name: string; email: string; password: string }>, { topic: 'user-created'; data: { id: number; name: string; email: string; password: string } }>
  }
}